export const courses = [
  {
    id: 1,
    title: 'The Ultimate Google Ads Training Course',
    author: 'Jerome Bell',
    category: 'marketing',
    price: 100,
    image: '/assets/images/courses/image-8.png',
  },
  {
    id: 2,
    title: 'Prduct Management Fundamentals',
    author: 'Marvin McKinney',
    category: 'management',
    price: 480,
    image: '/assets/images/courses/image-7.png',
  },
  {
    id: 3,
    title: 'HR Management and Analytics',
    author: 'Leslie Alexander Li',
    category: 'hr',
    price: 200,
    image: '/assets/images/courses/image-6.png',
  },
  {
    id: 4,
    title: 'Brand Management & PR Communications',
    author: 'Kristin Watson',
    category: 'marketing',
    price: 530,
    image: '/assets/images/courses/image-5.png',
  },
  {
    id: 5,
    title: 'Graphic Design Basic',
    author: 'Guy Hawkins',
    category: 'design',
    price: 500,
    image: '/assets/images/courses/image-4.png',
  },
  {
    id: 6,
    title: 'Business Development Management',
    author: 'Kathryn Murphy',
    category: 'management',
    price: 400,
    image: '/assets/images/courses/image-3.png',
  },
  {
    id: 7,
    title: 'Highload Software Architecture',
    author: 'Brooklyn Simmons',
    category: 'development',
    price: 600,
    image: '/assets/images/courses/image-2.png',
  },
  {
    id: 8,
    title: 'Human Resources – Selection and Recruitment',
    author: 'Kathryn Murphy',
    category: 'hr',
    price: 150,
    image: '/assets/images/courses/image-1.png',
  },
  {
    id: 9,
    title: 'User Experience. Human-centered Design',
    author: 'Cody Fisher',
    category: 'design',
    price: 240,
    image: '/assets/images/courses/image-0.png',
  },
  {
    id: 10,
    title: 'Social Media Strategy & Content',
    author: 'Wade Warren',
    category: 'marketing',
    price: 95,
    image: '/assets/images/courses/image-2.png',
  },
  {
    id: 11,
    title: 'Employee Performance Management',
    author: 'Jenny Wilson',
    category: 'hr',
    price: 220,
    image: '/assets/images/courses/image-5.png',
  },
  {
    id: 12,
    title: 'User Experience. Human-centered Design',
    author: 'Cody Fisher',
    category: 'design',
    price: 240,
    image: '/assets/images/courses/image-6.png',
  },
  {
    id: 13,
    title: 'Python for Backend Development',
    author: 'Devon Lane',
    category: 'development',
    price: 280,
    image: '/assets/images/courses/image-7.png',
  },
];
