export const courses = [
  {
    id: 1,
    title: 'Digital Marketing Fundamentals',
    author: 'John Smith',
    category: 'marketing',
    price: 49,
    image: null,
  },
  {
    id: 2,
    title: 'Project Management Essentials',
    author: 'Anna Brown',
    category: 'management',
    price: 59,
    image: null,
  },
  {
    id: 3,
    title: 'Talent Acquisition & Recruiting',
    author: 'Lisa Chen',
    category: 'hr',
    price: 39,
    image: null,
  },
  {
    id: 4,
    title: 'UI/UX Design Principles',
    author: 'Mark Davis',
    category: 'design',
    price: 69,
    image: null,
  },
  {
    id: 5,
    title: 'JavaScript for Beginners',
    author: 'Tom Wilson',
    category: 'development',
    price: 79,
    image: null,
  },
  {
    id: 6,
    title: 'Social Media Marketing',
    author: 'Sarah Lee',
    category: 'marketing',
    price: 44,
    image: null,
  },
  {
    id: 7,
    title: 'Agile & Scrum Masterclass',
    author: 'David Kim',
    category: 'management',
    price: 55,
    image: null,
  },
  {
    id: 8,
    title: 'Figma: Design from Scratch',
    author: 'Emma White',
    category: 'design',
    price: 62,
    image: null,
  },
  {
    id: 9,
    title: 'React Complete Guide',
    author: 'Alex Green',
    category: 'development',
    price: 89,
    image: null,
  },
  {
    id: 10,
    title: 'Employee Onboarding Strategies',
    author: 'Olivia Hall',
    category: 'hr',
    price: 35,
    image: null,
  },
  {
    id: 11,
    title: 'SEO & Content Strategy',
    author: 'Chris Martin',
    category: 'marketing',
    price: 48,
    image: null,
  },
  {
    id: 12,
    title: 'Python for Data Science',
    author: 'Nina Patel',
    category: 'development',
    price: 95,
    image: null,
  },
];
